// <auto-generated />
using DynamicList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DynamicList.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DynamicList.Models.Car", b =>
                {
                    b.Property<int>("carno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("carno"));

                    b.Property<string>("carname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("carpic")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("caryear")
                        .HasColumnType("integer");

                    b.HasKey("carno");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
